
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import {
  DynamicContextProvider,
  EthereumWalletConnectors,
  DynamicWagmiConnector,
  ZeroDevSmartWalletConnectors,
  SolanaWalletConnectors
} from "../lib/dynamic";

import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <DynamicContextProvider
        settings={{
          environmentId: "392bdadc-429a-42c8-8db0-f1193c84f1fb",
          walletConnectors: [SolanaWalletConnectors,ZeroDevSmartWalletConnectors, EthereumWalletConnectors],
        }}
      >
        <Providers>
          <DynamicWagmiConnector>
            <body className={inter.className}>{children}</body>
          </DynamicWagmiConnector>
        </Providers>
      </DynamicContextProvider>
    </html>
  );
}
